version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: pdb_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: pdb
    ports:
      - 28017:27017
    volumes:
      - ./db-data/:/data/db
      #- mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data_container: